version: '3.3'
services:
  s3:
    image: minio/minio:RELEASE.2021-06-14T01-29-23Z
    container_name: aws-s3
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    # command: 
    #   server /date
    command:
      minio gateway s3
    networks:
      - A
    # volumes:
    #   - ./s3:/date
  db:
      restart: always
      image: mysql/mysql-server:5.7.28
      container_name: mlflow_db
      expose:
          - "3306"
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
          - ./dbdata:/var/lib/mysql
      networks:
            - A
  mlflow:
      container_name: mlflow
      image: mlflow
      build:
          context: ./mlflow
          dockerfile: mlflow_dockerfile
      ports:
          - "5000:5000"
      environment: 
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - AWS_DEFAULT_REGION=${AWS_REGION}
          - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
      networks:
          - A
      entrypoint: ./wait-for-it.sh db:3306 -t 90 -- mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://${AWS_BUCKET_NAME}/ -h 0.0.0.0
  nginx:
        restart: always
        image: mlflow_nginx
        container_name: mlflow_nginx
        build:
          context: ./mlflow
          dockerfile: nginx_dockerfile
        ports:
            - "80:80"
        networks:
            - A
        depends_on:
            - mlflow
networks:
    A:
        driver: bridge